{% set name = "covsnap" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/enes-ak/covsnap/archive/v{{ version }}.tar.gz
  sha256: 1d656c2943ac315b03554f481921a0b7f8ea3bb92e98dc38b08be752b96ccf34

build:
  number: 0
  noarch: python
  entry_points:
    - covsnap = covsnap.cli:main
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=64
    - setuptools-scm >=8
  run:
    - python >=3.9
    - pysam >=0.22
    - numpy >=1.24
    - samtools >=1.17
    - htslib >=1.17
    - tabix
  run_constrained:
    # mosdepth is optional but recommended; constrain version if present
    - mosdepth >=0.3.4

test:
  imports:
    - covsnap
    - covsnap.cli
    - covsnap.engines
    - covsnap.annotation
  requires:
    - pytest
    - samtools
  source_files:
    - recipes/conda/test_generate_bam.py
    - recipes/conda/test_verify_tsv.py
    - recipes/conda/test_verify_report.py
  commands:
    - covsnap --version
    - python test_generate_bam.py
    - covsnap test_sorted.bam BRCA1 --raw-out test_raw.tsv --report-out test_report.md --engine samtools
    - test -f test_raw.tsv
    - test -f test_report.md
    - python test_verify_tsv.py
    - python test_verify_report.py
    - covsnap test_sorted.bam chr17:43044295-43125482 --raw-out test_region.tsv --report-out test_region.md --engine samtools
    - test -f test_region.tsv
    - rm -f test_sorted.bam test_sorted.bam.bai test_raw.tsv test_report.md test_region.tsv test_region.md

about:
  home: https://github.com/enes-ak/covsnap
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Coverage inspector for targeted sequencing QC (hg38)
  description: |
    covsnap computes per-target and per-exon depth metrics from
    BAM/CRAM files, producing a machine-readable raw TSV and a
    human-readable interpreted report with PASS/FAIL classifications.
    Supports gene symbols, genomic regions, and BED files as input.
    Ships with a bundled GENCODE v44 hg38 gene index — no internet
    or GTF files required at runtime.
  dev_url: https://github.com/enes-ak/covsnap
  doc_url: https://github.com/enes-ak/covsnap/blob/main/README.md

extra:
  recipe-maintainers:
    - enes-ak
  identifiers:
    - biotools:covsnap
  additional-platforms:
    - linux-aarch64
    - osx-arm64
